Mentions feature added
EOS-uiux-Solutions/user-story pull request #21
Opened 2021-06-13 15:20 UTC by mharshita

fixes: #15 

Mentions feature added.

2021-06-19 09:19 UTC, kbhutani0001 commented on src/assets/scss/components/comments.scss
> +.mentions--multiLine .mentions__input {
nested styles please

2021-06-19 09:20 UTC, kbhutani0001 commented on src/components/Comments.js
> +      setUsers(response.data.data.users)
null checks here please. if the request fails, this will break the app.

2021-08-09 20:16 UTC, kbhutani0001 commented
Why is this still draft @mharshita ?

2021-08-10 11:21 UTC, mharshita commented
@kbhutani0001  actually currently it is working like this : 

https://user-images.githubusercontent.com/60281688/128857318-9878b99f-6c94-4fa3-a601-2d04d39735c5.mp4

2021-08-16 13:41 UTC, mharshita commented
Through this PR we would be able to add mentions but mentioned usernames would not be converted to links.

2021-08-17 10:43 UTC, cyntss requested changes

2021-08-17 10:43 UTC, cyntss commented on .github/workflows/github-ci.yml
> +<<<<<<< HEAD
we need to remove these lines that come from a merge conflict

2021-08-17 10:43 UTC, cyntss commented on .github/workflows/github-ci.yml
> +=======
this one too

2021-08-17 10:43 UTC, cyntss commented on .github/workflows/github-ci.yml
> +>>>>>>> main
and this one

2021-08-17 11:09 UTC, mharshita commented
Done! thanks @cyntss :)

2021-09-16 11:57 UTC, cyntss approved these changes

2021-09-16 12:06 UTC, merged