Fix #235: Improved the UI if no story is found
EOS-uiux-Solutions/user-story pull request #236
Opened 2022-06-29 06:12 UTC by kailash360

**Issue Number**

fixes #235 

**Describe the changes you've made**

I have modified the UI if no story is found in the story list. I have also added a link to create a new story from the story list.

**Describe if there is any unusual behavior (Any Warning) of your code(Write `NA` if there isn't)**

NA

**Additional context (OPTIONAL)**

NA

**Test plan (OPTIONAL)**

A good test plan should give instructions that someone else can easily follow.

```cmd
npm run test
```

**Checklist**

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] The title of my pull request is a short description of the requested changes.

**Provide a Deployed link of route/page that needs to review**

Preview: Deploy preview link here with the appropriate route

![image](https://user-images.githubusercontent.com/75155230/176364226-35ec2d76-7cf3-4383-ab9b-cb6e30a9fa94.png)

2022-06-30 14:43 UTC, cyntss requested changes

2022-07-01 07:08 UTC, kailash360 commented on src/assets/scss/components/index.scss
> +@import './noStory.scss';
Alright

2022-07-01 07:08 UTC, kailash360 commented on src/components/NoStory.jsx
> +      <a href='/newStory' className='link'>
Done

2022-07-01 07:08 UTC, kailash360 commented on src/assets/scss/components/noStory.scss
> +  & p {
Sure, will keep that in mind

2022-07-01 08:46 UTC, cyntss commented
@kailash360 check that there are merge conflicts in the PR after my PR was merged. Let me know when you fix them so I can approve this PR

2022-07-01 08:57 UTC, kailash360 commented
> @kailash360 check that there are merge conflicts in the PR after my PR was merged. Let me know when you fix them so I can approve this PR

@cyntss 
I've resolved the conflicts and pushed

2022-07-01 08:57 UTC, kailash360 commented
> @kailash360 check that there are merge conflicts in the PR after my PR was merged. Let me know when you fix them so I can approve this PR

@cyntss 
I've resolved the conflicts and pushed

2022-07-01 11:37 UTC, merged