added okta basic integration
EOS-uiux-Solutions/user-story pull request #241
Opened 2022-07-06 19:39 UTC by codetheorem

Signed-off-by: Hrishikesh Agarwal <hrishikeshagarwalv@gmail.com>

**Issue Number**

fixes #

**Describe the changes you've made**

Added Basic Integration for Okta SSO

**Describe if there is any unusual behaviour (Any Warning) of your code(Write `NA` if there isn't)**

NA

**Additional context (OPTIONAL)**

Currently redirects you back to the sign-in page. The user profile is not updated.

**Test plan (OPTIONAL)**

1. Make SSO=true and add okta credentials as mentioned in the config.template.json.
2. Press the sign-in button on the home page.

**Checklist**

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] The title of my pull request is a short description of the requested changes.

2022-07-11 10:39 UTC, cyntss requested changes

2022-07-11 10:43 UTC, cyntss commented
@codetheorem also check that some tests are failing:

<img width="571" alt="image" src="https://user-images.githubusercontent.com/5013096/178247418-e463c1d6-09d4-4b5d-910a-24fe36c567d4.png">

2022-07-12 14:47 UTC, codetheorem commented on src/App.js
> +let oktaAuth
Fixed it.

2022-07-12 14:51 UTC, codetheorem commented
> @codetheorem also check that some tests are failing:
> 
> <img alt="image" width="571" src="https://user-images.githubusercontent.com/5013096/178247418-e463c1d6-09d4-4b5d-910a-24fe36c567d4.png">

Current testcases cannot accommodate the SSO integration. Should I add test cases in this PR or raise a another PR for that?

2022-07-19 10:49 UTC, cyntss approved these changes

2022-07-19 11:16 UTC, merged